apiVersion: '1'
axis: agent
author: lace
name: triage
version: v1.0.1
displayName: Triage
runtime:
  location: in-tree
  handlerId: lace/triage
trigger:
  producer: scanner
  hooks:
    available: []
    default: []
emits:
  manifestation: triage
configSchema:
  type: object
  additionalProperties: false
  properties: {}
